services:
  db:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    restart:
      always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messages_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: