services:
  web:
    container_name: api
    build:
      context: .
      dockerfile: docker/service.Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - db
      - kafka
    networks:
      - web_api

  db:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    restart:
      always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messages_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - web_api

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.3.2
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - web_api

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - web_api

volumes:
  pgdata:

networks:
  web_api:
    driver: bridge
