serviceName: message_processing_service
httpPort: :5001

postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDbname: messages_db
  PostgresqlSslmode: false
  PgDriver: pgx

kafka:
  brokers: [ "localhost:9092" ]
  groupID: message_processing_consumer
  initTopics: true