serviceName: message_processing_service
httpPort: :5001

postgres:
  PostgresqlHost: db
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDbname: messages_db
  PostgresqlSslmode: false
  PgDriver: pgx

kafka:
  brokers: [ "kafka:9092" ]
  groupID: message_processing_consumer
  initTopics: true

kafkaTopics:
  messageSaved:
    topicName: message_saved
    partitions: 5
    replicationFactor: 1